version: "3.9"

services:
  flask-app:
    build: .
    container_name: flask-ai
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped